"""Rename column

Revision ID: f891737c3c71
Revises: c0eb7dcfda13
Create Date: 2020-07-25 10:47:30.662740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f891737c3c71'
down_revision = 'c0eb7dcfda13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show', 'starte_date', new_column_name='start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show', 'start_date', new_column_name='starte_date')
    # ### end Alembic commands ###
