"""Add not nullable constraints

Revision ID: c1d6ef182247
Revises: dd1a1cd75a45
Create Date: 2020-10-25 11:25:25.875703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d6ef182247'
down_revision = 'dd1a1cd75a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'age',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('actors', 'gender',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('actors', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('movies', 'release_date',
                    existing_type=sa.DATE(),
                    nullable=False)
    op.alter_column('movies', 'title',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'title',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('movies', 'release_date',
                    existing_type=sa.DATE(),
                    nullable=True)
    op.alter_column('actors', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('actors', 'gender',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('actors', 'age',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
